# Generated by bin/generate_capability_report.exs; do not edit.
%{
  tursox: "0.2.1",
  engine: %{version: "0.7.2", cargo_features: [:fts, :pure_rust_crypto], crate: "turso"},
  experimental_features: %{
    strict: %{
      status: :supported,
      option: nil,
      builder: nil,
      cargo: nil,
      note: "always enabled compatibility no-op in the Rust builder"
    },
    attach: %{
      status: :supported,
      option: :attach,
      builder: :experimental_attach,
      cargo: nil,
      note: "file behavior is covered by the advanced schema suite"
    },
    autovacuum: %{
      status: :partial,
      option: :autovacuum,
      builder: :experimental_autovacuum,
      cargo: nil,
      note: "Tursox patches the exact 0.7.2 wrapper omission; the disabled gate errors and enabled update executes, but the fresh-file header remains mode 0 due the pinned early-halt path"
    },
    custom_types: %{
      status: :unsafe,
      option: :custom_types,
      builder: :experimental_custom_types,
      cargo: nil,
      note: "the flag is accepted, but a fresh custom-type database can SIGBUS during open and type-family probes are child-only"
    },
    encryption: %{
      status: :supported,
      option: :encryption,
      builder: :experimental_encryption,
      cargo: :pure_rust_crypto,
      note: "raw-key API wires with_encryption; all eight 0.7.2 cipher modes create, persist, reopen, reject wrong keys, and redact secrets"
    },
    generated_columns: %{
      status: :unsafe,
      option: :generated_columns,
      builder: :experimental_generated_columns,
      cargo: nil,
      note: "full create/insert/read succeeds on macOS but has produced SIGSEGV on Linux; explicit unsafe opt-in and child evidence are retained"
    },
    index_method: %{
      status: :supported,
      option: :index_method,
      builder: :experimental_index_method,
      cargo: :fts,
      note: "parser/index switch and deliberate Cargo FTS support are enabled"
    },
    materialized_views: %{
      status: :unsafe,
      option: :materialized_views,
      builder: :experimental_materialized_views,
      cargo: nil,
      note: "legacy alias for :views; CREATE MATERIALIZED VIEW reaches SIGBUS after open/connect on 0.7.2/macOS"
    },
    multiprocess_wal: %{
      status: :platform_limited,
      option: :multiprocess_wal,
      builder: :experimental_multiprocess_wal,
      cargo: nil,
      note: "64-bit local-filesystem Unix probe only; detailed release result below"
    },
    mvcc_passive_checkpoint: %{
      status: :unsafe,
      option: :mvcc_passive_checkpoint,
      builder: :experimental_mvcc_passive_checkpoint,
      cargo: nil,
      note: "runtime switch is exposed; PASSIVE checkpoint reaches SIGBUS after open/connect/write on 0.7.2/macOS"
    },
    runtime_extensions: %{
      status: :unsafe,
      option: :runtime_extensions,
      builder: :set_load_extension_enabled,
      cargo: nil,
      note: "explicit connection loader is exposed; libraries execute native code in the BEAM and must use Turso's extension ABI, not merely SQLite's ABI"
    },
    triggers: %{
      status: :supported,
      option: nil,
      builder: nil,
      cargo: nil,
      note: "always enabled compatibility no-op in the Rust builder"
    },
    vacuum: %{
      status: :unsafe,
      option: :vacuum,
      builder: :experimental_vacuum,
      cargo: nil,
      note: "the switch is exposed; initialized-file VACUUM currently reaches SIGBUS on 0.7.2/macOS and is child-only"
    },
    views: %{
      status: :unsafe,
      option: :views,
      builder: :experimental_materialized_views,
      cargo: nil,
      note: "ordinary views are always on; the documented flag enables materialized views, whose CREATE reaches SIGBUS on 0.7.2/macOS"
    },
    without_rowid: %{
      status: :supported,
      option: :without_rowid,
      builder: :experimental_without_rowid,
      cargo: nil,
      note: "explicit opt-in"
    }
  },
  statuses: [:supported, :partial, :unsupported, :platform_limited, :unsafe],
  categories: %{
    experimental: %{status: :partial, proof: ["test/experimental_capability_test.exs"]},
    extensions: %{
      status: :partial,
      proof: ["test/extension_inventory_test.exs", "test/runtime_extension_test.exs"]
    },
    types: %{status: :partial, proof: ["test/type_capability_test.exs"]},
    fts: %{status: :supported, proof: ["test/fts_test.exs"]},
    multiprocess_wal: %{
      status: :platform_limited,
      proof: ["test/multiprocess_access_test.exs", "test/multiprocess_recovery_test.exs"]
    },
    core_sql: %{status: :supported, proof: ["test/core_sql_regression_test.exs"]},
    pragmas: %{status: :partial, proof: ["test/pragma_capability_test.exs"]},
    schema: %{
      status: :partial,
      proof: ["test/view_capability_test.exs", "test/table_feature_test.exs",
       "test/storage_schema_test.exs"]
    }
  },
  report_version: 2
}
