# Generated by bin/generate_capability_report.exs; do not edit.
%{
  tursox: "0.2.0",
  engine: %{version: "0.7.2", cargo_features: [:fts], crate: "turso"},
  experimental_features: %{
    strict: %{
      status: :supported,
      option: nil,
      builder: nil,
      cargo: nil,
      note: "always enabled compatibility no-op in the Rust builder"
    },
    attach: %{
      status: :supported,
      option: :attach,
      builder: :experimental_attach,
      cargo: nil,
      note: "file behavior is covered by the advanced schema suite"
    },
    autovacuum: %{
      status: :unsupported,
      option: nil,
      builder: nil,
      cargo: nil,
      note: "documented experimental builder switch is absent from 0.7.2"
    },
    custom_types: %{
      status: :unsafe,
      option: :custom_types,
      builder: :experimental_custom_types,
      cargo: nil,
      note: "CREATE TYPE/domain enabled probes can terminate the process on the pin"
    },
    encryption: %{
      status: :unsupported,
      option: nil,
      builder: :experimental_encryption,
      cargo: :pure_rust_crypto,
      note: "no validated key/open contract; deliberately not exposed"
    },
    generated_columns: %{
      status: :unsafe,
      option: :generated_columns,
      builder: :experimental_generated_columns,
      cargo: nil,
      note: "reading generated values can terminate the process on the pin"
    },
    index_method: %{
      status: :supported,
      option: :index_method,
      builder: :experimental_index_method,
      cargo: :fts,
      note: "parser/index switch and deliberate Cargo FTS support are enabled"
    },
    materialized_views: %{
      status: :unsafe,
      option: :materialized_views,
      builder: :experimental_materialized_views,
      cargo: nil,
      note: "disabled gate is stable; enabled 0.7.2 probe can terminate the process"
    },
    multiprocess_wal: %{
      status: :platform_limited,
      option: :multiprocess_wal,
      builder: :experimental_multiprocess_wal,
      cargo: nil,
      note: "64-bit local-filesystem Unix probe only; detailed release result below"
    },
    mvcc_passive_checkpoint: %{
      status: :unsafe,
      option: nil,
      builder: :experimental_mvcc_passive_checkpoint,
      cargo: nil,
      note: "manual checkpoint probe can crash 0.7.2 and is rejected before allocation"
    },
    triggers: %{
      status: :supported,
      option: nil,
      builder: nil,
      cargo: nil,
      note: "always enabled compatibility no-op in the Rust builder"
    },
    vacuum: %{
      status: :partial,
      option: :vacuum,
      builder: :experimental_vacuum,
      cargo: nil,
      note: "requires an initialized file database"
    },
    views: %{
      status: :supported,
      option: nil,
      builder: nil,
      cargo: nil,
      note: "ordinary views are always enabled on 0.7.2"
    },
    without_rowid: %{
      status: :supported,
      option: :without_rowid,
      builder: :experimental_without_rowid,
      cargo: nil,
      note: "explicit opt-in"
    }
  },
  statuses: [:supported, :partial, :unsupported, :platform_limited, :unsafe],
  categories: %{
    experimental: %{status: :partial, proof: ["test/experimental_capability_test.exs"]},
    extensions: %{status: :partial, proof: ["test/extension_inventory_test.exs"]},
    types: %{status: :partial, proof: ["test/type_capability_test.exs"]},
    fts: %{status: :supported, proof: ["test/fts_test.exs"]},
    multiprocess_wal: %{
      status: :platform_limited,
      proof: ["test/multiprocess_access_test.exs", "test/multiprocess_recovery_test.exs"]
    },
    core_sql: %{status: :supported, proof: ["test/core_sql_regression_test.exs"]},
    pragmas: %{status: :partial, proof: ["test/pragma_capability_test.exs"]},
    schema: %{
      status: :partial,
      proof: ["test/view_capability_test.exs", "test/table_feature_test.exs",
       "test/storage_schema_test.exs"]
    }
  },
  report_version: 1
}
